In [203]:
# 自动重载外部文件的更新
import numpy as np
%load_ext autoreload
%autoreload 2

# 添加项目路径至path
import os
import sys
currentPath = os.path.join(os.getcwd(),"machinelearningIntro","机器学习实践/关联规则")
sys.path.append(currentPath)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [204]:
import pandas as pd
import numpy as np

In [205]:
datadir = r"D:\PythonEx\machinelearningIntro\机器学习实践\关联规则\data\ratings.csv"
df = pd.read_csv(datadir)

In [206]:
len(df)

1000209

In [207]:
df = df.head(100)

In [208]:
df

    userid  moveid  rating  timestamp
0        1    1193       5  978300760
1        1     661       3  978302109
2        1     914       3  978301968
3        1    3408       4  978300275
4        1    2355       5  978824291
..     ...     ...     ...        ...
95       2    2490       3  978299966
96       2    1834       4  978298813
97       2    3471       5  978298814
98       2     589       4  978299773
99       2    1690       3  978300051

[100 rows x 4 columns]

In [209]:
df1 = pd.get_dummies(df[['userid','moveid']],columns=["moveid"],prefix="",prefix_sep="")
df1

,userid,1,48,110,150,260,292,368,434,527,...,3114,3147,3186,3255,3256,3257,3408,3468,3471,3578
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
98,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [210]:
def func(x):
    if x.any():
        return 1
    else:
        return 0

In [211]:
%%time
inverted_table = df1.groupby("userid").agg(func)

CPU times: total: 62.5 ms
Wall time: 62.5 ms

In [212]:
inverted_table

,1,48,110,150,260,292,368,434,527,531,...,3114,3147,3186,3255,3256,3257,3408,3468,3471,3578
userid,,,,,,,,,,,,,,,,,,,,,
1,1,1,0,1,1,0,0,0,1,1,...,1,0,1,0,0,0,1,0,0,0
2,0,0,1,0,0,1,1,1,0,0,...,0,1,0,1,1,1,0,1,1,1

In [213]:
distinct_item_list = list(df["moveid"].drop_duplicates().sort_values().reset_index(drop=True))
len(distinct_item_list)

99

In [214]:
distinct_item_dict = dict(df["moveid"].drop_duplicates().sort_values().reset_index(drop=True))
len(distinct_item_dict)

99

In [215]:
distinct_item_dict

{0: 1,
 1: 48,
 2: 110,
 3: 150,
 4: 260,
 5: 292,
 6: 368,
 7: 434,
 8: 527,
 9: 531,
 10: 588,
 11: 589,
 12: 594,
 13: 595,
 14: 608,
 15: 647,
 16: 648,
 17: 661,
 18: 720,
 19: 745,
 20: 783,
 21: 902,
 22: 914,
 23: 919,
 24: 938,
 25: 1022,
 26: 1028,
 27: 1029,
 28: 1035,
 29: 1097,
 30: 1103,
 31: 1188,
 32: 1193,
 33: 1197,
 34: 1207,
 35: 1210,
 36: 1213,
 37: 1217,
 38: 1246,
 39: 1253,
 40: 1259,
 41: 1270,
 42: 1287,
 43: 1293,
 44: 1357,
 45: 1537,
 46: 1544,
 47: 1545,
 48: 1566,
 49: 1610,
 50: 1687,
 51: 1690,
 52: 1721,
 53: 1792,
 54: 1834,
 55: 1836,
 56: 1907,
 57: 1961,
 58: 1962,
 59: 2018,
 60: 2028,
 61: 2126,
 62: 2194,
 63: 2236,
 64: 2268,
 65: 2278,
 66: 2294,
 67: 2321,
 68: 2340,
 69: 2355,
 70: 2398,
 71: 2490,
 72: 2628,
 73: 2687,
 74: 2692,
 75: 2762,
 76: 2791,
 77: 2797,
 78: 2804,
 79: 2881,
 80: 2916,
 81: 2918,
 82: 3030,
 83: 3035,
 84: 3068,
 85: 3071,
 86: 3105,
 87: 3107,
 88: 3108,
 89: 3114,
 90: 3147,
 91: 3186,
 92: 3255,
 93: 3256,
 94: 3257,
 95: 3408,
 96: 3468,
 97: 3471,
 98: 3578}

In [216]:
inverted_table_arr = np.array(inverted_table)
inverted_table_arr

array([[1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
        1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1]], dtype=int64)

In [217]:
def like_the_same_two_items_users_list(data,item1,item2):
    return data.loc[(data[item1] == 1) & (data[item2] ==1)]

In [218]:
like_the_same_two_items_users_list(inverted_table, "1193", "661")

,1,48,110,150,260,292,368,434,527,531,...,3114,3147,3186,3255,3256,3257,3408,3468,3471,3578
userid,,,,,,,,,,,,,,,,,,,,,
1,1,1,0,1,1,0,0,0,1,1,...,1,0,1,0,0,0,1,0,0,0

In [219]:
def like_the_same_two_items_users_count(data,item1,item2):
    return len(data.loc[(data[item1] == 1) & (data[item2] ==1)])

In [220]:
like_the_same_two_items_users_count(inverted_table, "1", "48")

1

In [253]:
co_occurrence = pd.DataFrame(0,columns=distinct_item_list,index=distinct_item_list)
co_occurrence

,1,48,110,150,260,292,368,434,527,531,...,3114,3147,3186,3255,3256,3257,3408,3468,3471,3578
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
110,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
150,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3257,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3408,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3468,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3471,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3578,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [282]:
%%timeit
for i in co_occurrence.index:
    for j in co_occurrence.columns:
        co_occurrence.loc[i,j] = like_the_same_two_items_users_count(inverted_table,str(i),str(j))
co_occurrence

2.75 s ± 79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [283]:
%%timeit
co_occurrence1 = pd.DataFrame([[like_the_same_two_items_users_count(inverted_table,str(i),str(j)) for i in co_occurrence.index] for j in co_occurrence.columns])
co_occurrence1

2.2 s ± 21.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [276]:
def func2(cell,index_name,*new_arg):
    print(f"cell {cell}")
    # print(cell.__attr__)
    # column_name = str(cell.name)
    # print("index_name in func2 " + index_name)
    # print("column_name " + column_name)
    print(f"new_args{new_arg}")
    # return like_the_same_two_items_users_count(inverted_table,index_name,column_name)

In [277]:
def merge_record_in_an_hour(row):
    index_name = str(row.name)
    print("index_name in merge_record_in_an_hour " + index_name)
    # print(row)
    # print(type(row))
    return row.apply(func2,args = (index_name))

In [278]:
co_occurrence.apply(merge_record_in_an_hour, axis=0)

index_name in merge_record_in_an_hour 1
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
cell 0
new_args()
index_name in merge_record_in_an_hour 48
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
cell 0
new_args('8',)
index_name in merge_record_in_an_hour 110
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
cell 0
new_args('1', '0')
index_name in merge_record_in_an_hour 150
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
cell 0
new_args('5', '0')
index_name in merge_record_in_an_hour 260
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
cell 0
new_args('6', '0')
index_name in merge_record_in_an_hour 292
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
cell 0
new_args('9', '2')
index_name in merge_record_in_an_hour 368
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
cell 0
new_args('6', '8')
index_name in merge_record_in_an_hour 434
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
cell 0
new_args('3', '4')
index_name in merge_record_in_an_hour 527
cell 0
new_args('2', '7')
cell 0
new_args('2', '7')
cell 0
new_args('2', '7')
cell 0
new_args('2', '7')
cell 0
new_args('2', '7')
cell 0
new_args('2', '7')
cell 0
new_args('2', '7')
cell 0
new_args('2', '7')
cell 0

,1,48,110,150,260,292,368,434,527,531,...,3114,3147,3186,3255,3256,3257,3408,3468,3471,3578
1,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
48,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
110,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
150,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
260,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3257,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3408,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3468,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3471,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3578,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [245]:
a = pd.DataFrame(pd.Series([1,2,3]),columns=[1])
a.apply(func2,args=("48"))

TypeError: func2() takes 2 positional arguments but 3 were given

In [ ]:
    lambda x: x.apply(lambda d: apply_value,args= (x.name,))